#!/bin/sh
# Xsetup - run as root before the login dialog appears
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --pos 1080x353 --rotate normal --output DisplayPort-1 --mode 1920x1080 --pos 0x0 --rotate left --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 3000x0 --rotate right --output DVI-D-0 --off

